#!/bin/sh
sudo apt-get install wget -y
wget https://raw.githubusercontent.com/ohsayan/remove-ubuntu-boot-logo/next/ubuntu-logo.png
sudo mv /usr/share/plymouth/ubuntu-logo.png /usr/share/plymouth/ubuntu-logo.png.bak
sudo cp ubuntu-logo.png /usr/share/plymouth/ubuntu-logo.png
sudo update-initramfs -u
sudo update-grub
